---
# tasks file for repo_ppa
- fail: msg="This role is for Ubuntu systems only"
  when: ansible_distribution != "Ubuntu"

- name: Ensure ppa repository is installed
  apt_repository: repo='{{ name|mandatory }}' state='{{ state }}'

